public class Book {
    String[][] books = {
            {"The Catcher in the Rye"},
            {"To Kill a Mockingbird"},
            {"1984"},
            {"Pride and Prejudice"},
            {"The Great Gatsby"},
            {"The Hobbit"},
            {"The Da Vinci Code"},
            {"Harry Potter and the Sorcerer's Stone"},
            {"The Lord of the Rings: The Fellowship of the Ring"},
            {"The Hunger Games"},
            {"The Alchemist"},
            {"The Road"},
            {"A Game of Thrones"},
            {"The Girl with the Dragon Tattoo"},
            {"Gone Girl"},
            {"The Shining"},
            {"The Help"},
            {"The Fault in Our Stars"},
            {"The Martian"},
            {"The Handmaid's Tale"},
            {"Dune"},
            {"The Kite Runner"},
            {"The Picture of Dorian Gray"},
            {"A Brief History of Time"},
            {"The Count of Monte Cristo"},
            {"Frankenstein"},
            {"Sapiens: A Brief History of Humankind"},
            {"Brave New World"},
            {"The Odyssey"},
            {"Wuthering Heights"}

    };
}
